baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[[module.imports]]
    path = "github.com/dindinet/primo-startup-vercel"
    disabled = false

    [[module.imports.mounts]]
    source = "/"
    target = "static/"
